
bern-constant:
  entrypoint: "parametric:BatchBernoulliBandit"
  displayname: "Bernoulli - Constant batch ($B_\\ell=10$)"
  kwargs:
    means: simple6
    batchschedule: constant

bern-linear:
  entrypoint: "parametric:BatchBernoulliBandit"
  displayname: "Bernoulli - Linear batch ($B_\\ell=\\ell$)"
  kwargs:
    means: simple6
    batchschedule: linear

bern-quadratic:
  entrypoint: "parametric:BatchBernoulliBandit"
  displayname: "Bernoulli - Quadratic batch ($B_\\ell=\\ell^2$)"
  kwargs:
    means: simple6
    batchschedule: quadratic

bern-cubic:
  entrypoint: "parametric:BatchBernoulliBandit"
  displayname: "Bernoulli - Cubic batch ($B_\\ell=\\ell^3$)"
  kwargs:
    means: simple6
    batchschedule: cubic

bern-exp:
  entrypoint: "parametric:BatchBernoulliBandit"
  displayname: "Bernoulli - Exponential batch ($B_\\ell=2^\\ell$)"
  kwargs:
    means: simple6
    batchschedule: exp

bern-doubleexp:
  entrypoint: "parametric:BatchBernoulliBandit"
  displayname: "Bernoulli - Double-exponential batch ($B_\\ell=e^{2^\\ell}$)"
  kwargs:
    means: simple6
    batchschedule: doubleexp

bern-abrupt:
  entrypoint: "parametric:BatchBernoulliBandit"
  displayname: "Bernoulli - Abrupt batch schedule"
  kwargs:
    means: simple6
    batchschedule: abrupt


bern-exotic:
  entrypoint: "parametric:BatchBernoulliBandit"
  displayname: "Bernoulli - Exotic batch schedule"
  kwargs:
    means: simple6
    batchschedule: exotic1

trunc-constant:
  entrypoint: "parametric:BatchTruncatedGaussianBandit"
  kwargs:
    means: simple6
    batchschedule: constant

trunc-linear:
  entrypoint: "parametric:BatchTruncatedGaussianBandit"
  kwargs:
    means: simple6
    batchschedule: linear

trunc-quadratic:
  entrypoint: "parametric:BatchTruncatedGaussianBandit"
  kwargs:
    means: simple6
    batchschedule: quadratic

trunc-cubic:
  entrypoint: "parametric:BatchTruncatedGaussianBandit"
  kwargs:
    means: simple6
    batchschedule: cubic
trunc-exp:
  entrypoint: "parametric:BatchTruncatedGaussianBandit"
  kwargs:
    means: simple6
    batchschedule: exp

trunc-doubleexp:
  entrypoint: "parametric:BatchTruncatedGaussianBandit"
  kwargs:
    means: simple6
    batchschedule: doubleexp

trunc-abrupt:
  entrypoint: "parametric:BatchTruncatedGaussianBandit"
  kwargs:
    means: simple6
    batchschedule: abrupt

trunc-exotic:
  entrypoint: "parametric:BatchTruncatedGaussianBandit"
  kwargs:
    means: simple6
    batchschedule: exotic1